version: '2.1'

services:
  mysql:
   container_name: docker-mysql-lnkr
   image: mysql:latest
   environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
      - MYSQL_DATABASE=microcred
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass@word1
   ports:
   - "3306:3306"
   restart: always
   volumes:
      - /data/mysql

  tasktracker:
    image: backend-task-tracker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql-lnkr 
    ports:
      - 8083:8083