version: '2.1'

services:
  finalfrontend:
    image: finalfrontend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 30004200:30004200
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js